// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYzwqJMVFy7CxE4r3t-iHjIrBkNLsZs1o',
    appId: '1:715567807682:web:1096de7e1d8a1d53724f5b',
    messagingSenderId: '715567807682',
    projectId: 'simplequizapp-7ea52',
    authDomain: 'simplequizapp-7ea52.firebaseapp.com',
    databaseURL: 'https://simplequizapp-7ea52-default-rtdb.firebaseio.com',
    storageBucket: 'simplequizapp-7ea52.appspot.com',
    measurementId: 'G-8ND4E79TDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX-mJJyNE2ASJbwz_ZWJI6GogbcNZFezc',
    appId: '1:715567807682:android:ebd4d3fe11b19c04724f5b',
    messagingSenderId: '715567807682',
    projectId: 'simplequizapp-7ea52',
    databaseURL: 'https://simplequizapp-7ea52-default-rtdb.firebaseio.com',
    storageBucket: 'simplequizapp-7ea52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Xda1vIn-M-01_xe4v4x2fBZeWOO3vjg',
    appId: '1:715567807682:ios:4af80155d19f3ac1724f5b',
    messagingSenderId: '715567807682',
    projectId: 'simplequizapp-7ea52',
    databaseURL: 'https://simplequizapp-7ea52-default-rtdb.firebaseio.com',
    storageBucket: 'simplequizapp-7ea52.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Xda1vIn-M-01_xe4v4x2fBZeWOO3vjg',
    appId: '1:715567807682:ios:6cc68b7c81349c1d724f5b',
    messagingSenderId: '715567807682',
    projectId: 'simplequizapp-7ea52',
    databaseURL: 'https://simplequizapp-7ea52-default-rtdb.firebaseio.com',
    storageBucket: 'simplequizapp-7ea52.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
